### ISSUE TITLE
Are multiple Sqlite databases supported?

### ISSUE THREAD

**Issue by gavD** [liip/LiipFunctionalTestBundle#103]
Hello,

I have a Symfony2 project which accesses multiple databases and I've been unable to get it working with the otherwise wonderful LiipFunctionalTestBundle.

The application usually runs on PostGreSQL and I'm adding functional tests.

my config.test.yml looks like:

```
doctrine:
    dbal:
        default_connection: default
        types:
            point: Knp\DoctrineBehaviors\DBAL\Types\PointType
        connections:
            default:
                driver:   pdo_sqlite
                path:     %kernel.cache_dir%/test.db
                mapping_types:
                    point: point
            stats:
                driver:   pdo_sqlite
                path:     %kernel.cache_dir%/test_stats.db
                mapping_types:
                    point: point
```

test_stats.db is created but is 0 bytes

There is only one bundle that is set up to be in the stats db. Here's an extract from config.yml:

```
doctrine:
  dbal:        
    default_connection: default 
    connections: 
        default: 
            dbname: %database_name%
            user: %database_user%
            password: %database_password%
            host: %database_host%
            port: %database_port%
            driver:   %database_driver%        
            charset: UTF-8 
        stats: 
            dbname: %database_name_stats%
            user: %database_user%
            password: %database_password%
            host: %database_host%
            port: %database_port%
            driver:   %database_driver%        
            charset: UTF-8
orm:
    auto_generate_proxy_classes: %kernel.debug%
    default_entity_manager:   default
    entity_managers:
        default:
            result_cache_driver: apc
            connection:       default
            mappings:

                MyFAQBundle: ~
                MyMailBundle: ~
        stats:
            connection:       stats
            mappings:
                MyStatsBundle: ~
```

What I find is that test.db is all set up just fine, whereas test_stats.db is 0 bytes and no tables are created in there.

If I set everything up to use a single database everything works perfectly. I can see that the DriverChain in Doctrine definitely picks up MyStatsBundle\Entity but that's a separate chain to the main database.

Looking at https://github.com/liip/LiipFunctionalTestBundle/blob/master/Test/WebTestCase.php I am unsure as to whether it supports multiple databases or whether I'm totally missing the point?

I would appreciate any advice you can give me!
Thanks,
- Gav
