### ISSUE TITLE
Details on how to use the loginAs functionality 

### ISSUE THREAD

**Issue by phillipsnick** [liip/LiipFunctionalTestBundle#161]
I'm currently trying to test some secure sections of my application and came across the `loginAs` method on the WebTestCase class.

The documentation isn't very clear on how to actually utilise this feature and from what I can tell it doesn't actually work? But then I might be using it incorrectly. 

Also from looking at the below config example, this would never actually be used within this bundle?

```yaml
liip_functional_test:
    authentication:
        username: "a valid username"
        password: "the password of that user"
```
