### ISSUE TITLE
Specifying an entity manager when using the loadFixtures method

### ISSUE THREAD

**Issue by leksinteractive** [liip/LiipFunctionalTestBundle#485]
**Is your feature request related to a problem? Please describe.**
Hi team, I have two different bundles in my app and each one has their own entity manager. I am writing an integration test for a service in one of the bundles, but I need to load a fixture class from the second bundle. Is this currently possible?

**Describe alternatives you've considered**
I tried passing in the name of the entity manager for the fixture I'd like to load, in the `$omName` parameter of the `loadFixtures` method unsuccessfully. This was the main exception I kept getting:

`InvalidArgumentException: Doctrine ORM Manager named "shared" does not exist.`

I also tried different variations of the entity manager name but same outcome, eg:
"shared", "doctrine.orm.shared_entity_manager" and "shared_entity_manager":

**Additional context**
Here is part of my doctrine orm config with the two entity managers for more context:

```
orm:
    default_entity_manager: default
    auto_generate_proxy_classes: '%kernel.debug%'
    entity_managers:
        default:
            connection: client_database
            auto_mapping: true
        shared:
            connection: shared_database
            mappings:
                AdminBundle:
                    type: annotation
                    dir: '%kernel.project_dir%/src/AdminBundle/Entity'
                    prefix: AdminBundle\Entity
```

Thanks,
-Aleks
