### ISSUE TITLE
Unable to register fixture using sqlite

### ISSUE THREAD

**Issue by msechi** [liip/LiipFunctionalTestBundle#504]
composer.json (dev)
`"doctrine/doctrine-fixtures-bundle": "^3.1",
"liip/functional-test-bundle": "~2.0@alpha",` 

config/packages/test/doctrine.yaml
`doctrine:
    dbal:
      driver: 'pdo_sqlite'
      url: 'sqlite:///%kernel.project_dir%/var/test.db3'`

my test class
`class SimplestTest extends WebTestCase
{

private $fixtures;

public function setUp()
{
    $this->fixtures = $this->loadFixtures([
        MyFixtures::class
        ])->getReferenceRepository();
}

public function testToSeeIfItWorks()
{
    $this->assertTrue(true);
}
}`

my fixture class
`class MyFixtures extends AbstractFixture
{
public function load(ObjectManager $manager)
{

    $user1 = new User();
    $user1->setRoles(['ROLE_USER']);

    $manager->persist($user1);
    $manager->flush();

    $myFeed = new Feed();
    $myFeed->setName('Feed 1');
    $myFeed->setUrl('http://someurl');
    $myFeed->setUser($user1);

    $manager->persist($myFeed);
    $manager->flush();
}
}`

when I run the test I get this error:
`InvalidArgumentException: "App\Tests\DataFixtures\ORM\MyFixtures" is not a registered fixture`

thanks

**Comment by alexislefebvre** [comment]
IIRC, you have to declare the fixture as a service and tag it as a fixture.

**Comment by alexislefebvre** [comment]
This is documented in changelog and upgrade guide: https://github.com/liip/LiipFunctionalTestBundle/blob/4f94510b5c1c1758b9e7a284114a4643e38decb1/CHANGELOG.md#changed https://github.com/liip/LiipFunctionalTestBundle/blob/4f94510b5c1c1758b9e7a284114a4643e38decb1/UPGRADE-2.0.md

It should be added in fixtures documentation too.

---

Here is an example of usage:

```
services:
    _defaults:
        autowire: true
        autoconfigure: true
    Liip\Acme\Tests\App\DataFixtures\ORM\:
        resource: 'DataFixtures/ORM/*'
        tags: ['doctrine.fixture.orm']
```
