### ISSUE TITLE
Fatal error: Class 'Doctrine\Common\DataFixtures\ProxyReferenceRepository' not found

### ISSUE THREAD

**Issue by dan-klasson** [liip/LiipFunctionalTestBundle#76]
### I get an error using dev-master with Symfony 2.1.3.

Add this to `composer.json`:

```
"liip/functional-test-bundle": "dev-master"
```

To `AppKernel.php`:

```
$bundles[] = new Liip\FunctionalTestBundle\LiipFunctionalTestBundle();
```

To `app/config/config_test.yml`

```
liip_functional_test: ~

framework:
    test: ~
    session:
        storage_id: session.storage.filesystem
```

Add this to `src/Acme/DemoBundle/Tests/Controller/DemoControllerTest.php`:

```
use Liip\FunctionalTestBundle\Test\WebTestCase;

class DemoControllerTest extends WebTestCase
{
    public function testIndex()
    {
        $client = static::createClient();
        $this->loadFixtures(array());
```

Then run `phpunit -c app/` and get this error:

```
Fatal error: Class 'Doctrine\Common\DataFixtures\ProxyReferenceRepository' not found in /home/dan/Work/Symfony/vendor/liip/functional-test-bundle/Liip/FunctionalTestBundle/Test/WebTestCase.php on line 187
```
