### ISSUE TITLE
Handle master/slave connections

### ISSUE THREAD

**Issue by iamdto** [liip/LiipFunctionalTestBundle#96]
It would be great if we could handle master/slave connections. Currently it can not load database and tests fail when slaves connections are defined in the configuration.

Main configuration:

``` yaml
# app/config/config.yml
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   pdo_mysql
                host:     127.0.0.1
                port:     null
                dbname:   my_database
                user:     root
                password: 12345
                charset:  UTF8
                slaves:
                    slave1:
                        host:     null
                        port:     null
                        dbname:   my_database
                        user:     root
                        password: 12345
                        charset:  UTF8
```

Test configuration:

``` yaml
# app/config/config_test.yml
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   pdo_sqlite
                path:     %kernel.cache_dir%/test.db
```

`Liip\FunctionalTestBundle\Test\WebTestCase` expects this kind of parameters:

```
array(9) {
  'dbname' =>
  string(18) "my_database"
  'host' =>
  string(9) "127.0.0.1"
  'port' =>
  NULL
  'user' =>
  string(4) "root"
  'password' =>
  string(4) "12345"
  'charset' =>
  string(4) "UTF8"
  'driver' =>
  string(10) "pdo_sqlite"
  'path' =>
  string(53) "/my_project/app/cache/test/test.db"
  'driverOptions' =>
  array(0) {
  }
}
```

Whereas in this context it receives something like that:

```
array(5) {
  'driver' =>
  string(10) "pdo_sqlite"
  'slaves' =>
  array(1) {
    'slave1' =>
    array(7) {
      'dbname' =>
      string(18) "my_database"
      'host' =>
      NULL
      'port' =>
      NULL
      'user' =>
      string(4) "root"
      'password' =>
      string(4) "12345"
      'charset' =>
      string(4) "UTF8"
      'driver' =>
      string(10) "pdo_sqlite"
    }
  }
  'driverOptions' =>
  array(0) {
  }
  'master' =>
  array(8) {
    'dbname' =>
    string(18) "my_database"
    'host' =>
    string(9) "127.0.0.1"
    'port' =>
    NULL
    'user' =>
    string(4) "root"
    'password' =>
    string(4) "12345"
    'charset' =>
    string(4) "UTF8"
    'path' =>
    string(53) "/my_project/app/cache/test/test.db"
    'driver' =>
    string(10) "pdo_sqlite"
  }
  'wrapperClass' =>
  string(47) "Doctrine\DBAL\Connections\MasterSlaveConnection"
}
```

And here is the output of PHPUnit:

```
There was 1 error:

1) Acme\Bundle\DemoBundle\Tests\FooTest::testBar
Undefined index: dbname

/my_project/www/vendor/liip/functional-test-bundle/Liip/FunctionalTestBundle/Test/WebTestCase.php:254
```

I remember seeing the same problem in doctrine/DoctrineBundle#144 (which is now fixed).
